name: Update Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Pages
        run: python scripts/generate_pages.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          personal_token: ${{ secrets.WIKI_TOKEN }}
